### ISSUE TITLE
JRE Securerandom /usr/lib/jvm/jre/lib/security/java.security impact jar start very slowly(5~10min)

### ISSUE THREAD

**Issue by qiaofeng1227** [websoft9dev/role_jdk#1]
#2 Configure
- name: Setting JRE Securerandom
  lineinfile:
    path: /usr/lib/jvm/jre/lib/security/java.security
    regexp: 'securerandom.source=file:/dev/random'
    line: 'securerandom.source=file:/dev/./urandom'
  when: jdk_version == "8"

**Comment by qiaofeng1227** [comment]
add new softlink from /dev/random to /dev/./urandom

**Comment by zxc916684603** [comment]
in java 11, the path is: /usr/lib/jvm/java/conf/security/java.security
Suggest check  other paths, e.g java10, java12..

**Comment by qiaofeng1227** [comment]
Done
